chore: update controller-gen, regenerate manifests and bundle
Due to the previous dependency updates, the old version was incompatible and building the manager would fail:

Error: /home/runner/work/beegfs-csi-driver/beegfs-csi-driver/vendor/k8s.io/api/core/v1/doc.go:21:1: missing argument  (at <input>)